### ISSUE TITLE
菜鸟需要aishell3_wav_folder和mel_folder 里的资料

### ISSUE THREAD

**Issue by mcitew** [ranchlai/mandarin-tts#16]
Sorry if I am asking the repeated question as I am just a beginner. 

I followed the readme until the wav2mel.py requires two folders where I believe there are training data from some other websites. I would appreciate if you could share the link for place where I can download the data, or you could email me the information via mctiew8868@gmail.com

Thank you very much.

**Comment by Moonmore** [comment]
biaobei 数据集的官方链接失效了，可以找下相关的云盘链接。aishell3可以去openslr上直接下载

**Comment by mcitew** [comment]
请问是这里吗？
https://aishell-1-sample.oss-cn-beijing.aliyuncs.com/AISHELL-1_sample.zip

**Comment by mcitew** [comment]
我找到了另外一个，aishell-3.rar, 12.G，分成几个文件夹，整个12G都需要用到吗？

**Comment by Moonmore** [comment]
应该不是aishell1，aishell1是做asr和vpr的。标贝数据的名字应该是CSMSC，然后多说话人的语音数据是aishll3，那个数据是对的。

**Comment by mcitew** [comment]
好的，谢谢。
