### ISSUE TITLE
File not found running ../../mtts/train.py -c config.yaml -d cuda

### ISSUE THREAD

**Issue by mcitew** [ranchlai/mandarin-tts#17]
Here is my colab file, I am stuck at the 

%run ../../mtts/train.py -c config.yaml -d cuda

It says 'No such file or directory: '../../mel_folder/SSB10560130.npy'

Include please find my colab file.

https://colab.research.google.com/drive/13gXl3NQSz97Fl__9wmCQJulEODD7Xe5-?usp=sharing

**Comment by mcitew** [comment]
It is due to wrong training wave files have been used.

**Comment by everschen** [comment]
same issue, which one is wrong?
cd examples/aishell3
python ../../mtts/train.py -c config.yaml -d cuda
