### ISSUE TITLE
ckpt = torch.load(ckpt_file) 报错

### ISSUE THREAD

**Issue by wingdi** [ranchlai/mandarin-tts#8]
waveglow/ 里面的hubconf.py  200行 ckpt = torch.load(ckpt_file) 报错：
`RuntimeError: unexpected EOF, expected 459824 more bytes. The file might be corrupted.`
ckpt文件有问题了？
我的是ubuntu 2020, cuda version:11.3

**Comment by ranchlai** [comment]
试试删除了再重新下载。

**Comment by wingdi** [comment]
删除 waveglow重新下载还是这个问题， 是不是因为waveglow中 hubconf.py 200行的

` “https://api.ngc.nvidia.com/v2/models/nvidia/waveglow_ckpt_fp32/versions/19.09.0/files/nvidia_waveglowpyt_fp32_20190427” `

这个checkpoint的地址无效了，， 我浏览器访问这个地址，是空白页面 没有下载项。

我把这个链接放到迅雷里 显示的是个1.07GB的资源，但是下载时 下载到的却是个0KB的资源

**Comment by wingdi** [comment]
解决了，ckpt下载的不完整，当时以为它是ckpt-50000那个，搞错了
